#!/bin/bash -l
#SBATCH --chdir /scratch/saporito/Frag3D/
#SBATCH --job-name Frag3D
#SBATCH -o out_Frag3D.%j
#SBATCH -e err_Frag3D.%j
#SBATCH --account lsms
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --nodes 1
#SBATCH --time 72:00:00
#SBATCH --mem 7000

module purge
module restore akantu_env

echo STARTING AT $(date)

#TEST

srun /home/saporito/Frag3D/cpp/build/cpp/cohesive_sim -v 1000 -t 0.4 -T 1e-5 -msh "/home/saporito/Frag3D/input/mesh/plate_8.00e-03x8.00e-03x8.00e-04_npz3_P2.msh" -mat "/home/saporito/Frag3D/input/material/material_linear_nsn.dat" \
    --kappa 0.4 --center_x 0.0 --center_y 0.0 --z_sign 1.0 --cutoff 4e-3 --shape "gaussian" --angle_xz 0.0 --angle_yz 60.0


echo FINISHED AT $(date)